nodeLinker: pnp

packageExtensions:
  "@auth/drizzle-adapter@*":
    peerDependencies:
      drizzle-orm: "*"
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"
  "@preact/preset-vite@*":
    peerDependencies:
      "@babel/core": "*"
  "@testing-library/user-event@*":
    peerDependencies:
      "@testing-library/dom": "*"
  "drizzle-kit@*":
    peerDependencies:
      drizzle-orm: "*"
      postgres: "*"
  "eslint-config-next@*":
    peerDependencies:
      next: "*"
